name: Alerta DevOps ITLA

on:
  push:
    branches:
      - main

jobs:
  hola-mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Ejecutar Hola Mundo
        run: node index.js

      - name: Enviar notificación a ntfy
        run: |
          curl -H "Title: Hola Mundo - Jean carlos Cabral P. 2025-1380" \
               -H "Priority: default" \
               -d "GitHub Actions ITLA." \
               https://ntfy.sh/devops-itla